layout_spectrum: 1
favicon: null
name: Tstenig231
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0
  lightness: 0.8271501
  saturation: 0.7462057
  rhythmicContrast: 1
  brandColors:
    - '#C6D8E9'
    - '#F23865'
    - '#76A3BE'
    - '#395476'
    - '#271E20'
typography_spectrum: 0.7091063
