layout_spectrum: 0.31428511464037
favicon: null
name: Tstenig231
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.2231382089667022
  lightness: 0.6765957
  saturation: 0.5234042
  rhythmicContrast: 0.6553192
  brandColors:
    - '#BED8E9'
    - '#0D1504'
    - '#545C1F'
    - '#6E8091'
    - '#A0170D'
typography_spectrum: 0.2212766
