layout_spectrum: 0.2191489
favicon: null
name: Tstenig231
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.3988196
  lightness: 0.1191489
  saturation: 1
  rhythmicContrast: 0.5787234
  brandColors:
    - '#FEFFFF'
    - '#0F0F18'
    - '#727460'
    - '#98948A'
    - '#C3C5B1'
typography_spectrum: 0.4744681
