layout_spectrum: 0.6762226
favicon: null
name: Tstenig231
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  bucket: null
  version: null
  domain: null
color:
  brandStrength: 0.7436762
  lightness: 0.6045531
  saturation: 0.8929174
  rhythmicContrast: 0.4131535
  brandColors:
    - '#16300D'
    - '#88B439'
    - '#BDE05C'
    - '#FFFB03'
    - '#FFFDFF'
typography_spectrum: 0.8768972
