name: Tstenig231
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25302
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010506'
    - '#fefefe'
    - '#394158'
    - '#d5d8eb'
    - '#aeb3d0'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
